import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

import { Resvg } from '@resvg/resvg-js';

const GENERATED_MARKER = 'Generated by scripts/generate-case-study-svgs.mjs';
const DISALLOWED_FONT_SNIPPETS = ['IBM Plex Sans', 'IBM Plex Mono', 'Space Grotesk'];

function collectSvgFiles(path) {
  const stat = statSync(path);
  if (stat.isFile()) {
    return path.endsWith('.svg') ? [path] : [];
  }

  const files = [];
  for (const entry of readdirSync(path)) {
    files.push(...collectSvgFiles(join(path, entry)));
  }
  return files;
}

const targets = process.argv.slice(2);
const roots = targets.length > 0 ? targets : ['assets/images/case-studies'];
const svgFiles = roots.flatMap(collectSvgFiles);

if (svgFiles.length === 0) {
  console.error('No SVG files found to validate.');
  process.exit(1);
}

for (const filePath of svgFiles) {
  const source = readFileSync(filePath, 'utf8');

  if (filePath.startsWith('assets/images/case-studies/')) {
    if (!source.includes(GENERATED_MARKER)) {
      throw new Error(`Expected generated marker in ${filePath}`);
    }

    for (const fontSnippet of DISALLOWED_FONT_SNIPPETS) {
      if (source.includes(fontSnippet)) {
        throw new Error(`Unsupported standalone SVG font ${fontSnippet} in ${filePath}`);
      }
    }
  }

  const png = new Resvg(source).render().asPng();
  if (!png || png.length === 0) {
    throw new Error(`Failed to render ${filePath}`);
  }
  console.log(`ok ${filePath}`);
}