import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

import { Resvg } from '@resvg/resvg-js';
import opentype from 'opentype.js';

const GENERATED_MARKER = 'Generated by scripts/generate-case-study-svgs.mjs';
const DISALLOWED_FONT_SNIPPETS = ['IBM Plex Sans', 'IBM Plex Mono', 'Space Grotesk'];
const FONT_FILES = {
  sansRegular: 'node_modules/@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-400-normal.woff',
  sansBold: 'node_modules/@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-700-normal.woff',
  monoRegular: 'node_modules/@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff',
  monoBold: 'node_modules/@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-700-normal.woff',
};

function parseFont(filePath) {
  const buffer = readFileSync(filePath);
  const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
  return opentype.parse(arrayBuffer);
}

const FONT_METRICS = Object.fromEntries(
  Object.entries(FONT_FILES).map(([key, filePath]) => [key, parseFont(filePath)]),
);
const TEXT_WIDTH_EPSILON = 1;
// Must match MEASUREMENT_SAFETY_PAD in scripts/generate-case-study-svgs.mjs so
// the validator agrees with the generator about what "fits".
const MEASUREMENT_SAFETY_PAD = 1.012;

function fontMetricKey(kind, fontWeight) {
  const bold = Number(fontWeight ?? 400) >= 700;
  if (kind === 'mono') {
    return bold ? 'monoBold' : 'monoRegular';
  }
  return bold ? 'sansBold' : 'sansRegular';
}

function measureText(text, { kind, fontSize, fontWeight, letterSpacing }) {
  const metricKey = fontMetricKey(kind, fontWeight);
  const font = FONT_METRICS[metricKey];
  if (!font) {
    throw new Error(`Missing font metrics for ${metricKey}`);
  }

  const normalized = String(text);
  const advanceWidth = font.stringToGlyphs(normalized).reduce((sum, glyph) => sum + glyph.advanceWidth, 0);
  let width = (advanceWidth / font.unitsPerEm) * fontSize;
  if (normalized.length > 1) {
    width += (normalized.length - 1) * letterSpacing;
  }
  return width * MEASUREMENT_SAFETY_PAD;
}

function decodeXml(text) {
  return text
    .replaceAll('&quot;', '"')
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&amp;', '&');
}

function getAttribute(attributes, name) {
  const match = attributes.match(new RegExp(`${name}="([^"]*)"`));
  return match ? match[1] : null;
}

function validateMeasuredText(filePath, source) {
  const textTagPattern = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  for (const match of source.matchAll(textTagPattern)) {
    const [, attributes, content] = match;
    const maxWidth = Number(getAttribute(attributes, 'data-ab-max-width'));
    if (!Number.isFinite(maxWidth)) {
      continue;
    }

    const fontSize = Number(getAttribute(attributes, 'data-ab-font-size'));
    const fontWeight = Number(getAttribute(attributes, 'data-ab-font-weight') ?? '400');
    const letterSpacing = Number(getAttribute(attributes, 'data-ab-letter-spacing') ?? '0');
    const kind = getAttribute(attributes, 'data-ab-kind') ?? 'sans';
    const tspanPattern = /<tspan\b[^>]*>([\s\S]*?)<\/tspan>/g;

    const tspanTexts = [...content.matchAll(tspanPattern)].map(([, rawText]) => decodeXml(rawText));
    const inlineText = decodeXml(content.replace(/<[^>]+>/g, '').trim());
    const lineTexts = tspanTexts.length > 0 ? tspanTexts : inlineText ? [inlineText] : [];

    for (const text of lineTexts) {
      const width = measureText(text, { kind, fontSize, fontWeight, letterSpacing });
      if (width > maxWidth + TEXT_WIDTH_EPSILON) {
        throw new Error(`Text overflow detected in ${filePath}: \"${text}\" is ${width.toFixed(2)}px wide for a ${maxWidth}px slot`);
      }
    }

    // Vertical containment: when a cellBox is declared, the last line's bottom
    // must stay inside the cell. Catches paragraphs that wrap past a card edge.
    const cellYRaw = getAttribute(attributes, 'data-ab-cell-y');
    const cellHeightRaw = getAttribute(attributes, 'data-ab-cell-height');
    const textBottomRaw = getAttribute(attributes, 'data-ab-text-bottom');
    if (cellYRaw !== null && cellHeightRaw !== null && textBottomRaw !== null) {
      const cellBottom = Number(cellYRaw) + Number(cellHeightRaw);
      const textBottom = Number(textBottomRaw);
      if (textBottom > cellBottom + TEXT_WIDTH_EPSILON) {
        throw new Error(`Vertical overflow in ${filePath}: text extends to y=${textBottom.toFixed(1)} but its cell ends at y=${cellBottom.toFixed(1)} (overflow by ${(textBottom - cellBottom).toFixed(1)}px)`);
      }
    }
  }
}

function collectSvgFiles(path) {
  const stat = statSync(path);
  if (stat.isFile()) {
    return path.endsWith('.svg') ? [path] : [];
  }

  const files = [];
  for (const entry of readdirSync(path)) {
    files.push(...collectSvgFiles(join(path, entry)));
  }
  return files;
}

const targets = process.argv.slice(2);
const roots = targets.length > 0 ? targets : ['assets/images/case-studies', 'assets/images/andreabozzo-system-diagram.svg'];
const svgFiles = roots.flatMap(collectSvgFiles);

if (svgFiles.length === 0) {
  console.error('No SVG files found to validate.');
  process.exit(1);
}

for (const filePath of svgFiles) {
  const source = readFileSync(filePath, 'utf8');

  if (filePath.startsWith('assets/images/case-studies/')) {
    if (!source.includes(GENERATED_MARKER)) {
      throw new Error(`Expected generated marker in ${filePath}`);
    }

    if (!source.includes('data-ab-max-width=')) {
      throw new Error(`Missing text layout metadata in ${filePath}; regenerate SVG assets before validating.`);
    }

    for (const fontSnippet of DISALLOWED_FONT_SNIPPETS) {
      if (source.includes(fontSnippet)) {
        throw new Error(`Unsupported standalone SVG font ${fontSnippet} in ${filePath}`);
      }
    }

    validateMeasuredText(filePath, source);
  }

  if (source.includes('data-ab-max-width=')) {
    validateMeasuredText(filePath, source);
  }

  const png = new Resvg(source).render().asPng();
  if (!png || png.length === 0) {
    throw new Error(`Failed to render ${filePath}`);
  }
  console.log(`ok ${filePath}`);
}